### ISSUE TITLE
WebAssembly version

### ISSUE THREAD

**Issue by kaatt** [catdad-experiments/libheif-emscripten#10]
Having a wasm version of this would be much faster I believe!

**Comment by mishaschwartz** [comment]
Another advantage of a WASM version is that it would allow websites that enable a Content Security Policy to use it more securely. See https://github.com/strukturag/libheif/issues/173

**Comment by raxhvl** [comment]
I am working on a WASM build

**Comment by catdad** [comment]
@ravindranrahul that's great! I am happy to look at PRs or help where I can

**Comment by raxhvl** [comment]
I'm testing out a local build. I'll keep you posted once i get it working.

**Comment by raxhvl** [comment]
I was able to put together the wasm build https://github.com/ravindranrahul/heif-wasm. wasm binary loads asynchronously, I need to figure out how to initialize the post.js code correctly (I have manually moved post.js code to a custom script now). I'll then submit a PR to libheif and you may update your npm package.

**Comment by raxhvl** [comment]
I have created a PR strukturag/libheif#474

**Comment by jerbob92** [comment]
libheif now compiles to WASM by default: https://github.com/strukturag/libheif/pull/925

I have created the following ticket to make the maintainer of this repo aware: https://github.com/catdad-experiments/libheif-emscripten/issues/19

**Comment by catdad** [comment]
webassembly is now shipping in 1.17.1+
