### ISSUE TITLE
It does not work with avif images

### ISSUE THREAD

**Issue by Forux** [catdad-experiments/libheif-emscripten#15]
Hello, I just tested latest release, and it does not work with avif image. Test image can be opened even inside chrome, so it okay avif image.

Here is micro repo with example of the problem: https://github.com/Forux/libheif_wasm_error

**Comment by catdad** [comment]
avif is not supported by the web version of libheif: https://github.com/strukturag/libheif/issues/296

`libheif-emscripten` only compiles and distributes the js version of `libheif` in an easy to use way, but does not add any functionality. This would need to be implemented in `libheif`. You can follow up in the issue I linked if you'd like.
