### ISSUE TITLE
libheif now builds a WASM version

### ISSUE THREAD

**Issue by jerbob92** [catdad-experiments/libheif-emscripten#19]
Hello, I just wanted to let you know that a PR of mine has been merged into libheif to the emscripten build script (https://github.com/strukturag/libheif/pull/925), it now builds with the latest SDK and outputs WebAssembly by default. 

You will have to update your scripts to make that work correctly, or pass `USE_WASM=0` into the build script to get the same output as before.

This would also fix #10 afaik

**Comment by catdad** [comment]
webassembly is now shipping in 1.17.1+
